@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NDgxNzA0MTh9.Y8315_ry9ict5glxUvWRCxqH6ylDPapTFLBL1jmWYpU




### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Bruce Wayne",
  "email": "batman@example.com",
  "password": "password",
  "password_confirmation": "password"
}

### Users show

GET http://localhost:3000/users/1.json
Authorization: Bearer {{jwt}}

### Sessions create (login)

POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "batman@example.com",
  "password": "password"
}